/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  Signer,
  utils,
} from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface WithdrawLogicInterface extends utils.Interface {
  functions: {};

  events: {
    "EarningsWithdrawn(address,address,uint256)": EventFragment;
    "FeesWithdrawn(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "EarningsWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeesWithdrawn"): EventFragment;
}

export interface EarningsWithdrawnEventObject {
  owner: string;
  token: string;
  amount: BigNumber;
}
export type EarningsWithdrawnEvent = TypedEvent<
  [string, string, BigNumber],
  EarningsWithdrawnEventObject
>;

export type EarningsWithdrawnEventFilter =
  TypedEventFilter<EarningsWithdrawnEvent>;

export interface FeesWithdrawnEventObject {
  feeOwner: string;
  token: string;
  amount: BigNumber;
}
export type FeesWithdrawnEvent = TypedEvent<
  [string, string, BigNumber],
  FeesWithdrawnEventObject
>;

export type FeesWithdrawnEventFilter = TypedEventFilter<FeesWithdrawnEvent>;

export interface WithdrawLogic extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WithdrawLogicInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "EarningsWithdrawn(address,address,uint256)"(
      owner?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      amount?: PromiseOrValue<BigNumberish> | null
    ): EarningsWithdrawnEventFilter;
    EarningsWithdrawn(
      owner?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      amount?: PromiseOrValue<BigNumberish> | null
    ): EarningsWithdrawnEventFilter;

    "FeesWithdrawn(address,address,uint256)"(
      feeOwner?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      amount?: PromiseOrValue<BigNumberish> | null
    ): FeesWithdrawnEventFilter;
    FeesWithdrawn(
      feeOwner?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      amount?: PromiseOrValue<BigNumberish> | null
    ): FeesWithdrawnEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
